---
title: Bibliography
---

S. Widgren, S. Engblom, U. Emanuelson and A. Lindberg (2018)
Spatio-temporal modelling of verotoxigenic *Escherichia coli* O157 in
cattle in Sweden: Exploring options for control. *Veterinary Research*
49:78.  [DOI:
10.1186/s13567-018-0574-2](https://doi.org/10.1186/s13567-018-0574-2)

R. Eriksson, S. Engblom, S. Widgren (2018) Towards Bayesian
Parametrization of national scale epidemics. MATHMOD 2018 Extended
Abstract Volume​, ARGESIM Report 55 (ISBN 978-3-901608-91-9), p 65-66.
[DOI: 10.11128/arep.55.a55245](https://doi.org/10.11128/arep.55.a55245)

P. Bauer (2017) Parallelism in Event-Based Computations with
Applications in Biology. Doctoral thesis, Department of Information
Technology, Uppsala University,
Sweden. http://urn.kb.se/resolve?urn=urn:nbn:se:uu:diva-332009

S. Engblom, S. Widgren (2017) Chapter 11 - Data-Driven Computational
Disease Spread Modeling: From Measurement to Parametrization and
Control, Editor(s): Arni S.R. Srinivasa Rao, Saumyadipta Pyne,
C.R. Rao, In Handbook of Statistics, Elsevier, Volume 36, Pages
305--328. [DOI: 10.1016/bs.host.2017.05.005](https://doi.org/10.1016/bs.host.2017.05.005)

P. Bauer, S. Engblom, and S. Widgren (2016) Fast event-based
epidemiological simulations on national scales. *International Journal
of High Performance Computing Applications* 30(4),
438-453. [DOI: 10.1177/1094342016635723](https://doi.org/10.1177/1094342016635723)

S. Widgren, S. Engblom, P. Bauer, J. Fr&ouml;ssling, U. Emanuelson,
and A. Lindberg (2016) Data-driven network modeling of disease
transmission using complete population movement data: Spread of VTEC
O157 in Swedish cattle. *Veterinary Research*
47:81. [DOI: 10.1186/s13567-016-0366-5](https://doi.org/10.1186/s13567-016-0366-5)

S. Widgren (2016) Studies on verotoxigenic *Escherichia coli* O157 in
Swedish cattle: From sampling to disease spread modelling. Doctoral
thesis, Department of Clinical Sciences, Swedish University of
Agricultural Sciences,
Sweden. http://pub.epsilon.slu.se/13821/

S. Widgren, P. Bauer, and S. Engblom (2016) SimInf: An R package for
Data-driven Stochastic Disease Spread Simulations. The SimInf manual
available via [arXiv](http://arxiv.org/abs/1605.01421).

P. Bauer (2015) Parallelism and Efficiency in Discrete-Event
Simulation. Licentiate thesis, Department of Information Technology,
Uppsala University,
Sweden. http://www.it.uu.se/research/publications/lic/2015-004/

## Talks

**S. Widgren**, S. Engblom, U Emanuelson,
  A. Lindberg,*"Spatio-temporal modelling of VTEC O157 in cattle in
  Sweden: Exploring options for control"*, 13 December 2018, Glasgow,
  Scotland.

**S. Widgren**, S. Engblom, U Emanuelson,
  A. Lindberg,*"Spatio-temporal modelling of VTEC O157 in cattle in
  Sweden: Exploring options for control"* at [Modelling in Animal
  Health conference - ModAH
  2017](https://workshop.inra.fr/modah2017/), 14--16 June 2017,
  Nantes, France.

**S. Engblom**, [Data-driven computational
  Epidemics](http://www.maths.lu.se/kalendarium/?event=data-driven-computational-epidemics),
  6 March 2017, Lund, Sweden.

**S. Engblom**, [Data-driven Epidemiological Simulations:
Verotoxigenic E. coli
O157](http://www.birs.ca/workshops/2016/16w5041/files/Stefan_Engblom_BIRS.pdf)
at the workshop [Mathematical Biology for Understanding Emerging
Infectious Diseases at the Human-Animal-Environment Interface: a "One
Health"
Approach"](http://www.birs.ca/events/2016/5-day-workshops/16w5041),
November 20--25 2016 in Banff, Canada. The lecture was video recorded
[mp4](http://videos.birs.ca/2016/16w5041/201611240925-Engblom.mp4).

**S. Widgren**, P. Bauer, and S. Engblom, *"SimInf; an R-tool for
data-driven modelling of disease spread and control"* at the 14th
ISVEE Conference - International Symposium on Veterinary Epidemiology
and Economics, 6 November 2015 Merida, Mexico.

**S. Widgren**, P. Bauer, and S. Engblom, *"Efficient data-driven
simulation of infection spread in the Swedish cattle population"* at
the minisymposium ["Data-driven modelling of
epidemics"](http://user.it.uu.se/~stefane/formalia/ProgramDDE.pdf) at
the 9th European Conference on Mathematical and Theoretical Biology
(ECMTB) 6 June 2014, Gothenburg, Sweden.

## Workshops

Stefan Widgren and Robin Eriksson, *"Infectious disease modelling with
SimInf"* at the National Veterinary Institute, Uppsala, Sweden. 9th
May 2019.

Stefan Widgren, *"Infectious disease modelling with SimInf"* at the
Institute of Biodiversity, Animal Health & Comparative Medicine,
University of Glasgow, Scotland. Friday 14th December 2018.

Stefan Widgren and Thomas Rosendal, *"Infectious disease modelling
with SimInf"* at the 2017 Society for Veterinary Epidemiology and
Preventive Medicine ([SVEPM](http://www.svepm2017.org/programme/))
annual conference, 29th March 2017 Inverness, Scotland.

## Posters

Robin Eriksson, *"Towards Bayesian Parametrization of national scale
epidemics"* at Workshop IV: Uncertainty Quantification for Stochastic
Systems and Applications. Part of the Long Program Complex
High-Dimensional Energy Landscapes. 13--17 November 2017. IPAM at UCLA,
Los Angeles, US.

A. Comin, S. Widgren, E. &Aring;gren, A. Lindberg, ["Data-driven
stochastic modelling of Salmonella Dublin infection in dairy
herds"](http://www.svepm.org.uk/f-Download-d-file.html?id=1098) at the
2015 Society for Veterinary Epidemiology and Preventive Medicine
([SVEPM](http://www.svepm.org.uk/f-Download-d-file.html?id=1254))
annual conference, 25--27 March 2015 Gent, Belgium.
